name: actions-test
on: 
   workflow_dispatch:
     inputs:
       userName:
         description: "Username"
         required: true
         default: "Diablo"
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Username: ${{ github.event.inputs.username }}"
          echo  "Actor's username: ${{ github.actor }}"
