name: "ArgoCD sync"
on: "push"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone reposiory"
        uses: actions/checkout@v2
        with:
          repository: "Manoj-07/argocd-example-apps.git"
          ref: "master"
      - name: Sync ArgoCD Application
        uses: omegion/argocd-app-actions@master
        with:
          address: "argocd-manoj.com"
          token: ${{ secrets.ARGOCD_TOKEN }}
          appName: "guestbook"